context:
  name: scitiff
  version: 25.7.0
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/scitiff-${{ version }}.tar.gz
  sha256: 677051d83f02b8bcc41320cc2ba613df9cb9ee78b2e02b9639c2c4f3232e0f87

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - scitiff-dev-dump-schemas = scitiff._schema:dump_schemas
      - scitiff-dump-metadata-example = scitiff.executables:dump_metadata_example

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=68
    - setuptools-scm >=8.0
    - pip
  run:
    - python >=${{ python_min }} 
    - scipp
    - tifffile
    - jsonschema
    - pydantic

tests:
  - python:
      imports:
        - scitiff
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - scitiff-dev-dump-schemas --help
      - scitiff-dump-metadata-example --help

about:
  summary: Scientific tiff format for imaging experiments.
  description: |
    SciTiff format inherits HyperStacks and define metadata on top of the HyperStacks.
    Scitiff project hosts both metadata schema and io helpers to save/load scitiff images.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://scipp.github.io/scitiff/
  repository: https://github.com/scipp/scitiff
  documentation: https://scipp.github.io/scitiff/

extra:
  recipe-maintainers:
    - YooSunYoung
    - conda-forge/scipp
